Repository WhatTheSong/WhatTheSong-Server, pull requests merged in 2023-02, with the labels that each got.

#16 Feat/#11 카카오/애플 소셜 로그인 리팩토리
  config/baseResponseStatus.js
  config/express.js
  package-lock.json
  package.json
  src/app/User/passport/index.js
  src/app/User/userController.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: Refactor, 러코, 회원

#18 Feat/#17 사용자 이름 변경 및 푸시 알람 동의 여부 변경 기능 구현
  config/baseResponseStatus.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: Feat, 러코, 회원

#37 Feat/#36 추천 게시판
  src/app/Board/boardController.js
  src/app/Board/boardDao.js
  src/app/Board/boardProvider.js
  src/app/Board/boardService.js
Labels: Comment, 미닝, 게시글 공통

#47 Feat/#32 게시판, 댓글 신고 기능 구현
  config/appleOauth/AuthKey_N646Z5SRX5.p8
  config/appleStrategy.js
  config/baseResponseStatus.js
  config/express.js
  src/app/Board/boardService.js
  src/app/Comment/commentDao.js
  src/app/Comment/commentProvider.js
  src/app/Comment/commentService.js
  src/app/Report/reportController.js
  src/app/Report/reportDao.js
  src/app/Report/reportProvider.js
  src/app/Report/reportRoute.js
  src/app/Report/reportService.js
Labels: Feat, 러코, 신고

#49 [Fix] status 수정 완료
  src/app/Board/boardDao.js
Labels: Fix, 미닝, 게시글 공통

#54 [Fix] patch부분 validation 처리 추가
  src/app/Board/boardController.js
  src/app/Board/boardDao.js
  src/app/Board/boardProvider.js
Labels: Fix, 미닝, 게시글 공통

#65 Feat/#64 fileUrl response api 삭제
  config/baseResponseStatus.js
  src/app/Board/boardController.js
  src/app/Board/boardDao.js
  src/app/Board/boardService.js
Labels: Chore, 미닝, 게시글 공통
